### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by kevinjos** [noisebridge/rfid-access-control#8]
Might be cool, what do you think...?

I want to use [Sourcegraph](https://sourcegraph.com) for rfid-access-control code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/hzeller/rfid-access-control. (It should only take 30 seconds.)

Thank you!

**Comment by hzeller** [comment]
Sure, why not. Check out
https://sourcegraph.com/github.com/hzeller/rfid-access-control
